### ISSUE TITLE
Warning: Uncaught TypeError: Cannot read property 'condition' of undefined

### ISSUE THREAD

**Issue by sanchezzzhak** [AivanF/WSTester#1]
```
s.hws.onmessage = function(t) {
            var e = JSON.parse(t.data);
            s.add("- Got:", 1),
            s.add(n(t.data), 1);
            var o = s.flows[s.current_flow][s.current_unit]
              , r = !1;
<u><b>            if (o.condition) {</b></u>
                var h = o.condition(e);
            }
```

заменить на `o && o.hasOwnProperty('condition'); `
так как переменная может быть undefined

**Comment by AivanF** [comment]
Благодарю за замечание! Действительно, в Safari эта ошибка не выводится, а в Chrome я в консоль не заглядывал, так как всё работало корректно. Уже обновил код, добавил комментарии и несколько проверок на корректность индексов в нужных местах.
